import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import '@/app/globals.css'
import ThemeWrapper from "@/components/ThemeWrapper"
import HeaderPublic from "@/components/headers/HeaderPublic"
import Footer from '@/components/CustomerFooter/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "EnUnaÓptica",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeWrapper>
          <HeaderPublic />
          {children}
           <Footer />
        </ThemeWrapper>
      </body>
    </html>
  )
}
